name: Test against Rails main

on:
  schedule:
    - cron: "0 0 * * *" # Run every day at 00:00 UTC
  workflow_dispatch:
  push:

jobs:
  main:
    name: Ruby${{ matrix.ruby }} rails_main
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.3'
    env:
      CI: true
      BUNDLE_GEMFILE: gemfiles/rails_main.gemfile

    steps:
      - uses: zendesk/checkout@v3
      - uses: zendesk/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake test
